// <auto-generated />
namespace CRUD.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class __second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(__second));
        
        string IMigrationMetadata.Id
        {
            get { return "201905112209377__second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
